# Generated by Django 6.0.6 on 2026-06-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_platformapikey_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier for the frontend to fetch.', max_length=100, unique=True)),
                ('section', models.CharField(default='General', help_text='e.g. LandingPage, Footer, About', max_length=50)),
                ('content', models.TextField(help_text='The actual text/HTML content.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
