# Generated by Django 6.0.6 on 2026-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_preset',
            field=models.CharField(blank=True, help_text='Preset avatar name e.g. male_bear', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_avatar',
            field=models.URLField(blank=True, help_text='Google profile picture URL', max_length=500, null=True),
        ),
    ]
