# Generated by Django 6.0.6 on 2026-06-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=15),
        ),
    ]
