# Generated by Django 6.0.6 on 2026-06-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_advertisement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='banner_image',
            field=models.ImageField(upload_to='ads/'),
        ),
    ]
