# Generated by Django 6.0.6 on 2026-06-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
    ]
