# Generated by Django 6.0.6 on 2026-06-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECHARGE', 'Wallet Recharge'), ('LEAD_UNLOCK', 'Lead Contact Unlock'), ('SUBSCRIPTION', 'Subscription Purchase')], db_index=True, max_length=20),
        ),
    ]
