# Generated by Django 6.0.6 on 2026-06-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECHARGE', 'Wallet Recharge'), ('LEAD_UNLOCK', 'Lead Contact Unlock'), ('SUBSCRIPTION', 'Subscription Purchase'), ('VERIFICATION', 'Verification Badge Purchase'), ('FEATURE', 'Featured Listing Purchase')], db_index=True, max_length=20),
        ),
    ]
