# Generated by Django 6.0.6 on 2026-06-20 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_transaction_reference_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_to_inviter', models.PositiveIntegerField(default=25)),
                ('reward_to_new_user', models.PositiveIntegerField(default=500)),
                ('status', models.CharField(default='SUCCESS', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_invitations', to=settings.AUTH_USER_MODEL)),
                ('new_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
