# Generated by Django 6.0.6 on 2026-06-19 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessportfolio',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='businesses.businessprofile'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='businesses.category'),
        ),
        migrations.AddField(
            model_name='lead',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_received', to='businesses.businessprofile'),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['category', 'is_available'], name='businesses__categor_3589bf_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['experience'], name='businesses__experie_ccf92b_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['hourly_rate'], name='businesses__hourly__1a44c8_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['location'], name='businesses__locatio_55cd76_idx'),
        ),
    ]
