# Generated by Django 6.0.6 on 2026-06-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_businessprofile_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/'),
        ),
    ]
