# Generated by Django 6.0.6 on 2026-06-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='plan_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='FREE', max_length=15),
        ),
    ]
