# Generated by Django 6.0.6 on 2026-06-18 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_businessprofile_service_areas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['experience'], name='businesses__experie_ccf92b_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['hourly_rate'], name='businesses__hourly__1a44c8_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['location'], name='businesses__locatio_55cd76_idx'),
        ),
    ]
