# Generated by Django 6.0.6 on 2026-06-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_businessprofile_businesses__experie_ccf92b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
